# app/models.py
from sqlalchemy import Column, Integer, String, Text, Enum, TIMESTAMP, SmallInteger, Boolean
from sqlalchemy.dialects.mysql import TINYINT, MEDIUMINT
from .db import Base

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, autoincrement=True)
    language_id = Column(TINYINT, default=1)
    username = Column(String(255))
    password = Column(String(255), nullable=False)
    group = Column(Integer, nullable=False)
    description = Column(Text)
    profile_image = Column(String(255))
    contact_number = Column(String(60))
    email = Column(String(255), nullable=False)
    email_verified_at = Column(TIMESTAMP)
    actual_email = Column(String(255))
    title = Column(String(100))
    firstname = Column(String(100))
    lastname = Column(String(100))
    telephone = Column(String(25))
    telephone_old = Column(String(25))
    fax = Column(String(25))
    mobile = Column(String(25))
    address_line_1 = Column(String(500))
    postcode = Column(String(12))
    country_id = Column(MEDIUMINT)
    newsletter = Column(Enum('0', '1'), default='0')
    receive_offer_emails = Column(TINYINT(1), default=0, nullable=False)
    last_offer_email_sent_at = Column(TIMESTAMP)
    last_login = Column(Integer)
    login_hash = Column(String(255))
    profile_fields = Column(Text)
    created_at = Column(Integer)
    updated_at = Column(Integer)
    active = Column(Enum('0', '1'), default='0', nullable=False)
    activate_hash = Column(String(128))
    verified_at = Column(Integer)
    forgot_rand = Column(String(255))
    forgot_at = Column(Integer)
    address_line_2 = Column(String(45))
    town = Column(String(45))
    footer_email_content = Column(Text)
    footer_signature = Column(Text)
    is_exported = Column(TINYINT(1), default=0)
    color = Column(String(255))
    turnoff_whatsapp = Column(TINYINT, default=0)
    whatsapp_token = Column(String(255), default='0')
    whatsapp_id = Column(String(255), default='0')
    remember_token = Column(String(300))
